--[[
    RCU Kaitun Engine — Do NOT edit this file
    This is loaded by the settings script automatically
    
    By Ducky
]]

local S = _G.RCUSettings
if not S then warn("[RCU Kaitun] No settings found. Set _G.RCUSettings first."); return end

if not game:IsLoaded() then game.Loaded:Wait() end

local RS = game:GetService("ReplicatedStorage")
local Players = game:GetService("Players")
local LP = Players.LocalPlayer
local Workspace = game:GetService("Workspace")
local CollectionService = game:GetService("CollectionService")
local HttpService = game:GetService("HttpService")
local Lighting = game:GetService("Lighting")
local UIS = game:GetService("UserInputService")
local TeleportService = game:GetService("TeleportService")

local requestFunc = (syn and syn.request) or (http and http.request) or request

pcall(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/SenhorLDS/ProjectLDSHUB/refs/heads/main/Anti%20AFK"))() end)

local Knit = require(RS.Packages.Knit)
Knit.OnStart():await()

local ClickService = Knit.GetService("ClickService")
local EggService = Knit.GetService("EggService")
local RebirthService = Knit.GetService("RebirthService")
local TreeService = Knit.GetService("TreeService")
local AxeService = Knit.GetService("AxeService")
local InventoryService = Knit.GetService("InventoryService")
local PetService = Knit.GetService("PetService")
local RewardService = Knit.GetService("RewardService")
local UpgradeService = Knit.GetService("UpgradeService")
local SeasonService = Knit.GetService("SeasonService")
local AuraService = Knit.GetService("AuraService")
local EventService = Knit.GetService("EventService")
local OrbService = Knit.GetService("OrbService")
local FarmService = Knit.GetService("FarmService")
local BuildingService = Knit.GetService("BuildingService")
local ClanService = Knit.GetService("ClanService")
local HiveService = Knit.GetService("HiveService")
local LumberjackService = Knit.GetService("LumberjackService")

local DataController = Knit.GetController("DataController")
local EggController = Knit.GetController("EggController")
local HatchingController = require(LP.PlayerScripts.Client.Controllers.HatchingController)
local ClickController = require(LP.PlayerScripts.Client.Controllers.ClickController)

local Functions = require(RS.Shared.Functions)
local Util = require(RS.Shared.Util)
local Values = require(RS.Shared.Values)
local seasonVars = require(RS.Shared.Variables)

DataController:waitForData()
local sessionStart = os.time()
local eggsThisSession = 0

local function pd() return DataController:getData() end
local function safe(fn) pcall(fn) end
local function loop(delay, fn) task.spawn(function() while true do safe(fn); task.wait(delay) end end) end

print("[RCU Kaitun] Engine loaded. Starting systems...")

-- ══════════════════════════════════════════════
-- STAT GUI
-- ══════════════════════════════════════════════
if S.StatGUI and S.StatGUI.Enable then
    local sg = Instance.new("ScreenGui")
    sg.Name = "RCU_Stats"
    sg.DisplayOrder = 999998
    sg.IgnoreGuiInset = true
    sg.ResetOnSpawn = false

    local frame = Instance.new("Frame")
    frame.Size = UDim2.new(0, 220, 0, 200)
    frame.Position = UDim2.new(0, 8, 0.5, -100)
    frame.BackgroundColor3 = Color3.fromRGB(10, 10, 15)
    frame.BackgroundTransparency = 0.3
    frame.BorderSizePixel = 0
    frame.Parent = sg
    Instance.new("UICorner", frame).CornerRadius = UDim.new(0, 6)

    local ttl = Instance.new("TextLabel")
    ttl.Size = UDim2.new(1, 0, 0, 20)
    ttl.Position = UDim2.new(0, 0, 0, 4)
    ttl.BackgroundTransparency = 1
    ttl.Text = "RCU Kaitun"
    ttl.TextColor3 = Color3.fromRGB(120, 100, 255)
    ttl.TextSize = 13
    ttl.Font = Enum.Font.GothamBold
    ttl.Parent = frame

    local sl = Instance.new("TextLabel")
    sl.Size = UDim2.new(1, -16, 1, -28)
    sl.Position = UDim2.new(0, 8, 0, 26)
    sl.BackgroundTransparency = 1
    sl.Text = "Loading..."
    sl.TextColor3 = Color3.fromRGB(180, 180, 200)
    sl.TextSize = 11
    sl.Font = Enum.Font.RobotoMono
    sl.TextXAlignment = Enum.TextXAlignment.Left
    sl.TextYAlignment = Enum.TextYAlignment.Top
    sl.Parent = frame

    sg.Parent = LP.PlayerGui

    loop(2, function()
        local d = pd()
        if not d then return end
        local elapsed = os.time() - sessionStart
        local honeyAm = 0
        pcall(function() local h = Util.itemUtils.getItemFromName(d, "honey"); honeyAm = h and h:getAmount() or 0 end)
        local bestName, bestMult = "None", 0
        pcall(function()
            if d.inventory and d.inventory.pet then
                for _, pData in pairs(d.inventory.pet) do
                    local obj = Util.itemUtils.createItemFromData(pData)
                    if obj then local m = obj:getMultiplier(); if m > bestMult then bestMult = m; bestName = obj:getName() end end
                end
            end
        end)
        local eq = 0
        if d.equippedPets then for _ in pairs(d.equippedPets) do eq = eq + 1 end end
        local lines = {
            string.format("Session: %02d:%02d:%02d", math.floor(elapsed/3600), math.floor(elapsed%3600/60), elapsed%60),
            "Clicks: " .. Functions.suffixes(d.clicks or 0),
            "Rebirths: " .. Functions.suffixes(d.rebirths or 0),
            "Gems: " .. Functions.suffixes(d.gems or 0),
            "Honey: " .. Functions.suffixes(honeyAm),
            "Skulls: " .. Functions.suffixes(d.skulls or 0),
            "Prestige: " .. (d.prestige or 0),
            "Pets: " .. eq .. " equipped",
            "Best: " .. bestName,
            "Eggs: " .. eggsThisSession .. " (session)",
        }
        sl.Text = table.concat(lines, "\n")
        frame.Size = UDim2.new(0, 220, 0, 26 + #lines * 14)
    end)
end

-- ══════════════════════════════════════════════
-- PERFORMANCE
-- ══════════════════════════════════════════════
if S.BlackScreen then
    local bsg = Instance.new("ScreenGui"); bsg.Name="RCU_Black"; bsg.DisplayOrder=999999; bsg.IgnoreGuiInset=true; bsg.ResetOnSpawn=false
    local bg = Instance.new("Frame",bsg); bg.Size=UDim2.new(1,0,1,0); bg.BackgroundColor3=Color3.new(0,0,0); bg.BorderSizePixel=0
    local lbl = Instance.new("TextLabel",bg); lbl.Size=UDim2.new(1,0,0,24); lbl.Position=UDim2.new(0,0,0,8); lbl.BackgroundTransparency=1; lbl.Text="RCU Kaitun Active | F3 or Wake Up to toggle"; lbl.TextColor3=Color3.fromRGB(60,60,60); lbl.TextSize=12; lbl.Font=Enum.Font.Gotham
    local btn = Instance.new("TextButton",bg); btn.Size=UDim2.new(0,160,0,40); btn.Position=UDim2.new(0.5,-80,0.5,-20); btn.BackgroundColor3=Color3.fromRGB(25,25,25); btn.Text="Wake Up"; btn.TextColor3=Color3.fromRGB(100,100,100); btn.TextSize=14; btn.Font=Enum.Font.GothamBold; btn.BorderSizePixel=0
    Instance.new("UICorner",btn).CornerRadius=UDim.new(0,6)
    btn.MouseButton1Click:Connect(function() bsg.Enabled = not bsg.Enabled end)
    UIS.InputBegan:Connect(function(i,g) if not g and i.KeyCode == Enum.KeyCode.F3 then bsg.Enabled = not bsg.Enabled end end)
    bsg.Parent = LP.PlayerGui
end
if S.DisableParticles then loop(5, function() for _,o in ipairs(Workspace:GetDescendants()) do if o:IsA("ParticleEmitter") or o:IsA("Trail") or o:IsA("Beam") or o:IsA("Fire") or o:IsA("Smoke") or o:IsA("Sparkles") then o.Enabled=false end end end) end
if S.LowQualityTerrain then pcall(function() local t=Workspace:FindFirstChildOfClass("Terrain"); t.Decoration=false; t.WaterWaveSize=0; t.WaterWaveSpeed=0; t.WaterTransparency=1 end) end
if S.RemoveTextures then loop(10, function() for _,o in ipairs(Workspace:GetDescendants()) do if o:IsA("Texture") or o:IsA("Decal") then o.Transparency=1 end end end) end
if S.DisableShadows then pcall(function() Lighting.GlobalShadows=false end) end
if S.HideGameUI then pcall(function() LP.PlayerGui:FindFirstChild("MainUI").Enabled=false end) end
if S.FPSCap and S.FPSCap > 0 and setfpscap then pcall(function() setfpscap(S.FPSCap) end) end
if S.AggressiveGC then loop(10, function() collectgarbage("collect") end) end

-- ══════════════════════════════════════════════
-- AUTO CLICK
-- ══════════════════════════════════════════════
if S.AutoClick then loop(0.02, function() ClickController:setLastClickType(2); ClickController:setDebounce(); ClickController:doClick() end) end

-- ══════════════════════════════════════════════
-- AUTO HATCH
-- ══════════════════════════════════════════════
if S.HideHatchAnimation then
    HatchingController._realAnim = HatchingController._realAnim or HatchingController.playEggAnimation
    HatchingController.playEggAnimation = function() return nil end
end
if S.AutoHatch then
    task.spawn(function()
        local EggsModule = require(RS.Shared.List.Pets.Eggs)
        while true do
            if not HatchingController._isHatching then
                safe(function()
                    local d = pd()
                    local best = nil
                    local highMap = 0
                    if d.maps then for id in pairs(d.maps) do local n=tonumber(id); if n and n>highMap then highMap=n end end end
                    for name, data in pairs(EggsModule) do
                        if data.requiredMap == highMap and (data.currency == "clicks" or not data.currency) then best=name; break end
                    end
                    if best then
                        local args = {best, 99}
                        if S.UseLuckyEggs then for id in pairs(EggController._luckyEggs or {}) do table.insert(args, {luckyEggId=id}); break end end
                        EggService.openEgg._re:FireServer(unpack(args))
                        eggsThisSession = eggsThisSession + 1
                    end
                end)
            end
            task.wait(0.17)
        end
    end)
end

-- ══════════════════════════════════════════════
-- AUTO REBIRTH
-- ══════════════════════════════════════════════
if S.AutoRebirth then
    loop(0.5, function()
        local Rebirths = require(RS.Shared.List.Rebirths)
        local Vars = require(RS.Shared.Variables)
        local d = pd(); local best,bestAm = nil,0
        for idx,am in pairs(Rebirths) do
            local price = (Vars.rebirthPrice+(d.rebirths or 0)*Vars.rebirthPriceMultiplier)*am + Vars.rebirthPriceMultiplier*(am*(am-1)/2)
            if (d.clicks or 0) >= price and am > bestAm then bestAm=am; best=idx end
        end
        if best then RebirthService:rebirth(best) end
    end)
end

-- ══════════════════════════════════════════════
-- AUTO BUY UPGRADES + SKILLS
-- ══════════════════════════════════════════════
if S.AutoBuyUpgrades then
    loop(1, function()
        local d=pd(); local U=require(RS.Shared.List.Upgrades)
        for id,def in pairs(U) do
            if not(def.requiredMap and not d.maps[def.requiredMap]) then
                local lvl=(d.upgrades[id] or 0)+1; local c=def.upgrades[lvl]
                if c and c.cost <= d.gems then UpgradeService:upgrade(id); task.wait(0.1) end
            end
        end
    end)
end
if S.AutoUpgradeSkills then
    loop(10, function()
        local STS=require(RS.Packages.Knit.KnitClient).GetService("SkillTreeService")
        local ST=require(RS.Shared.List.SkillTree); local d=pd()
        for catId,cat in pairs(ST) do for sub,subD in pairs(cat.list) do for i in ipairs(subD.list) do
            local k=sub.."_"..i
            if not(d.skillTree and d.skillTree[catId] and d.skillTree[catId][k]) then STS:buySkillTree(tostring(catId),sub,i); task.wait(0.15) end
        end end end
    end)
end

-- ══════════════════════════════════════════════
-- FARMS
-- ══════════════════════════════════════════════
if S.AutoBuyFarms then loop(10, function() local d=pd(); local F=require(RS.Shared.List.Farms); for fid,info in pairs(F) do if info.price and not info.isNotFarm and fid~="farmer" and (d.gems or 0)>=info.price and not(d.farms and d.farms[fid]) then FarmService:buy(fid); task.wait(0.5) end end end) end
if S.AutoUpgradeFarms then loop(5, function() local d=pd(); local F=require(RS.Shared.List.Farms); for fid,info in pairs(F) do if d.farms and d.farms[fid] and info.upgrades then local lvl=(d.farms[fid].stage or 0)+1; local n=info.upgrades[lvl]; if n and (d.gems or 0)>=(n.price or 0) then FarmService:upgrade(fid); task.wait(0.2) end end end end) end
if S.AutoClaimFarms then loop(10, function() local F=require(RS.Shared.List.Farms); for fid in pairs(F) do if not fid:lower():find("farmer") then FarmService:claim(fid); task.wait(0.1) end end end) end

-- ══════════════════════════════════════════════
-- PETS
-- ══════════════════════════════════════════════
if S.AutoEquipBestPets then loop(5, function() local b=LP.PlayerGui:FindFirstChild("MainUI",true) and LP.PlayerGui.MainUI:FindFirstChild("EquipBest",true); if b then local c=b:FindFirstChild("Click") or b; for _,cn in pairs(getconnections(c.MouseButton1Down)) do cn:Fire() end; for _,cn in pairs(getconnections(c.MouseButton1Up)) do cn:Fire() end end end) end
if S.CraftAllPets then loop(5, function() local d=pd(); if d.inventory and d.inventory.pet then for id,data in pairs(d.inventory.pet) do if (data.am or 0)>=5 then PetService:craft({[1]=id},true,1); task.wait(0.3) end end end end) end

-- ══════════════════════════════════════════════
-- BEE HIVE
-- ══════════════════════════════════════════════
if S.AutoCollectHoney then loop(S.HoneyCollectDelay or 5, function() if (pd().honeyToCollect or 0)>0 then HiveService:collectHoney() end end) end
if S.AutoOpenCapsules then
    loop(0.5, function()
        local d=pd(); local C=require(RS.Shared.List.Skylands.Capsules); local cap=C[S.CapsuleIndex or 1]; if not cap then return end
        local honey=0; pcall(function() local h=Util.itemUtils.getItemFromName(d,"honey"); honey=h and h:getAmount() or 0 end)
        local HU=require(RS.Shared.List.Hive.HiveUpgrades)
        local capMax=3+(d.hiveUpgrades and d.hiveUpgrades.capsulesMaxOpen and HU.capsulesMaxOpen.upgrades[d.hiveUpgrades.capsulesMaxOpen] and HU.capsulesMaxOpen.upgrades[d.hiveUpgrades.capsulesMaxOpen].value or 0)
        local maxOpen=math.clamp(math.floor(honey/cap.price),0,capMax)
        if maxOpen>=1 then HiveService:openCapsule(S.CapsuleIndex or 1, maxOpen) end
    end)
end
if S.AutoUpgradeHive then
    loop(5, function()
        local HU=require(RS.Shared.List.Hive.HiveUpgrades); local d=pd()
        local honey=0; pcall(function() local h=Util.itemUtils.getItemFromName(d,"honey"); honey=h and h:getAmount() or 0 end)
        for uid,ud in pairs(HU) do if ud.upgrades then local cur=d.hiveUpgrades and d.hiveUpgrades[uid] or 0; local nxt=ud.upgrades[cur+1]; if nxt then local cost=nxt.cost and nxt.cost:getAmount() or 0; if honey>=cost then HiveService:buyHiveUpgrade(uid); task.wait(0.2) end end end end
    end)
end
if S.AutoEquipBestBees then
    loop(10, function()
        local d=pd(); if not d.inventory or not d.inventory.bee then return end
        local bees={}; for id,data in pairs(d.inventory.bee) do local obj=Util.itemUtils.createItemFromData(data); if obj then for i=1,(data.am or 1) do table.insert(bees,{id=id,mult=obj:getMultiplier()}) end end end
        table.sort(bees,function(a,b) return a.mult>b.mult end)
        local maxB=3; pcall(function() maxB=Values.maxBees(LP,d) end); maxB=math.floor(maxB)
        local toEq={}; for i=1,math.min(maxB,#bees) do toEq[bees[i].id]=true end
        local eq=d.equippedBees or {}
        for id in pairs(eq) do if not toEq[id] then HiveService:unequipBee(id); task.wait(0.2) end end
        for id in pairs(toEq) do if not eq[id] then HiveService:equipBee(id); task.wait(0.2) end end
    end)
end
if S.AutoCraftBees then
    loop(10, function()
        local d=pd(); if not d.inventory or not d.inventory.bee then return end
        for id,data in pairs(d.inventory.bee) do
            local obj=Util.itemUtils.createItemFromData(data); if not obj then continue end
            local am=data.am or 1; local isSh=obj.isShiny and obj:isShiny() or false; local isRb=obj.isRainbow and obj:isRainbow() or false
            if S.CraftBeeType=="shiny" and not isSh and not isRb and am>=150 then HiveService:craftBee(id,"shiny"); task.wait(0.5)
            elseif S.CraftBeeType=="rainbow" and isSh and not isRb and am>=10 then HiveService:craftBee(id,"rainbow"); task.wait(0.5) end
        end
    end)
end
if S.AutoClaimBeedex then loop(15, function() pcall(function() local BR=require(RS.Shared.List.Hive.BeedexRewards); local d=pd(); local n=0; for _ in pairs(d.beedex or {}) do n=n+1 end; for _,r in ipairs(BR) do if n>=r.required then HiveService:claimBeedexReward(r.required); task.wait(0.5) end end end) end) end
if S.AutoBuyHoneyMerchant then loop(30, function() for i=1,6 do pcall(function() HiveService:buyHoneyMerchant(i) end); task.wait(0.3) end end) end
if S.AutoBuyHoneyShop then loop(30, function() for i=1,10 do pcall(function() HiveService:buyHoneyShop(i) end); task.wait(0.3) end end) end

-- ══════════════════════════════════════════════
-- CLAIMS
-- ══════════════════════════════════════════════
if S.AutoPickUp then loop(0.5, function() local orbs=Workspace:FindFirstChild("Debris") and Workspace.Debris:FindFirstChild("Orbs"); if not orbs then return end; local hrp=LP.Character and LP.Character:FindFirstChild("HumanoidRootPart"); if not hrp then return end; local c={}; for _,o in ipairs(orbs:GetChildren()) do if o:IsA("BasePart") then o:SetAttribute("canCollect",true); o.Anchored=true; table.insert(c,o.Name) end end; if #c>0 then OrbService.collectOrbs:Fire(c) end end) end
if S.PickupStars then loop(0.5, function() local hrp=LP.Character and LP.Character:FindFirstChild("HumanoidRootPart"); local deb=Workspace:FindFirstChild("Debris"); if not hrp or not deb then return end; for _,s in ipairs(deb:GetChildren()) do if s.Name=="FallingStar" and s.PrimaryPart then local h=s.PrimaryPart:FindFirstChild("hideAfterLanding"); if h then local f=false; for _,p in ipairs(h:GetChildren()) do if p:IsA("ParticleEmitter") and p.Enabled then f=true; break end end; if not f then firetouchinterest(hrp,s.PrimaryPart,0); firetouchinterest(hrp,s.PrimaryPart,1); break end end end end end) end
if S.AutoClaimAchievements then loop(10, function() local A=require(RS.Shared.List.Achievements); local d=pd(); for k,v in pairs(A) do local l=1; for c in pairs(d.claimedAchievements) do if c:find(k) then l=l+1 end end; if #v.list>=l and v.list[l].amount<=v.getValue(d) then RewardService:claimAchievement(k); task.wait(0.5) end end end) end
if S.AutoClaimPlaytime then loop(15, function() local h=LP.PlayerGui.MainUI.Menus.RewardsFrame.Main.Displays.Playtime.Holder; for _,f in ipairs(h:GetChildren()) do if f:IsA("Frame") then local t=f:FindFirstChild("Main",true) and f.Main:FindFirstChild("Timer"); if t and t.Text=="Claim" then RewardService:claimPlaytimeReward(tonumber(f.Name)); task.wait(0.5) end end end end) end
if S.AutoClaimDaily then loop(30, function() local d=pd(); if workspace:GetServerTimeNow()-d.dayReset>=86400 and math.max(0,600-(d.dailyRewardRequiredTime or 0))<=0 then RewardService:claimDailyReward() end end) end
if S.AutoPrestige then loop(10, function() local PS=Knit.GetService("PrestigeService"); local Pr=require(RS.Shared.List.Prestige.Prestiges); local d=pd(); local n=Pr[(d.prestige or 0)+1]; if n and (d.prestigeXp or 0)>=n.required then PS:claim() end end) end
if S.AutoClaimIndex then loop(10, function() local IS=Knit.GetService("IndexService"); local IR=require(RS.Shared.List.IndexRewards); local PC=Knit.GetController("PetController"); local d=pd(); local cnt=Util.indexUtils.countIndex(d,PC:getExistTable()); for rid,rd in pairs(IR) do if cnt>=(rd.required or 0) and not table.find(d.claimedIndexRewards or {},rid) then IS:claimIndexReward(rid); task.wait(0.5) end end end) end
if S.AutoClaimChests then loop(15, function() local Ch=require(RS.Shared.List.Chests); for cid in pairs(Ch) do RewardService:claimChest(cid); task.wait(0.1) end end) end
if S.OpenSupplyDrops then loop(3, function() local deb=Workspace:FindFirstChild("Debris"); if deb then for _,d in ipairs(deb:GetChildren()) do if d.Name:find("SupplyDropEvent") then for _,o in ipairs(d:GetChildren()) do local p=o:FindFirstChild("ProximityPrompt"); if p then pcall(fireproximityprompt,p) end end end end end end) end
if S.AutoClaimSeasonPass then
    loop(10, function()
        local d=pd(); local sn=seasonVars.season; local su=Util.seasonUtils; local lvl=su.getPassLevel(d)
        local prem=d[("season%dPassPremium"):format(sn)]; local claimed=d[("season%dPassClaimed"):format(sn)]
        for tier=1,lvl do for track=1,(prem and 2 or 1) do local k=("%d%d"):format(track,tier); if not claimed[k] then SeasonService:claimTier(tier,track); task.wait(0.3) end end end
        local allDone=true; for tier=1,14 do if tier>lvl then allDone=false; break end; for track=1,(prem and 2 or 1) do if not claimed[("%d%d"):format(track,tier)] then allDone=false; break end end; if not allDone then break end end
        if allDone then SeasonService:resetPass() end
    end)
end

-- ══════════════════════════════════════════════
-- QUESTS / WHEELS / MERCHANT
-- ══════════════════════════════════════════════
if S.AutoAngelQuest then loop(5, function() local AQ=require(RS.Shared.List.AngelQuests); local d=pd(); local t=d.angelQuestTier or 1; if t<=#AQ and (d.angelQuestProgress or 0)>=AQ[t].quest.amount then Knit.GetService("QuestService"):claimAngelQuest() end end) end
if S.AutoSpinClanWheel then loop(60, function() ClanService:clanWheelSpin() end) end
if S.AutoSpinBoostWheel then loop(60, function() RewardService:boostWheelSpin() end) end
if S.AutoSpinAdminWheel then loop(5, function() Knit.GetService("AdminAbuseService"):adminWheelSpin() end) end
if S.AutoBuyAncientMerchant then
    loop(10, function()
        local AM=require(RS.Shared.List.AncientMerchant); local d=pd(); local bought=d.ancientMerchantBought or {}
        for slot=1,Values.ancientMerchantSlots(LP,d) do
            local ts=DateTime.fromUnixTimestamp(Knit.serverTimeNow+3600):ToUniversalTime()
            local seed=ts.Year*222+ts.Month*333+ts.Day*444444+ts.Hour*33333+LP.UserId+slot
            local item=AM[Functions.getRandom(AM,seed)]
            if item then local nm=(item.item.nm or ""):lower(); if (nm:find("global") or nm:find("egg")) and not bought[tostring(seed)] then
                local tickets=0; if d.inventory and d.inventory.exclusive then for _,it in pairs(d.inventory.exclusive) do if it.nm=="ancientTicket" then tickets=it.am or 0; break end end end
                if tickets>=item.price then RewardService:buyAncientMerchant(slot); task.wait(1) end
            end end
        end
    end)
end

-- ══════════════════════════════════════════════
-- GARDEN / ITEMS / DICE / METEORS
-- ══════════════════════════════════════════════
if S.AutoPlantClaim then
    loop(10, function()
        local GS=Knit.GetService("GardenService"); local Plants=require(RS.Shared.List.Skylands.Plants); local d=pd()
        if d.gardenPlants then for i=1,5 do local p=d.gardenPlants[tostring(i)]
            if p and p.plantName then local info=Plants[p.plantName]; if info and (p.plantedAt+info.duration)-Knit.serverTimeNow<=0 then
                for _,model in pairs(CollectionService:GetTagged("gardenPlant")) do if model:GetAttribute("gardenId")==i then local pr=model:FindFirstChildOfClass("ProximityPrompt"); if pr and pr.Enabled then pcall(fireproximityprompt,pr) end end end
            end else local Seeds=require(RS.Shared.List.Skylands.Seeds); for st in pairs(Seeds) do GS:plantSeed(st,i); task.wait(0.2); break end end
        end end
    end)
end
if S.AutoUseBoxes then loop(5, function() local d=pd(); if d.inventory and d.inventory.box then for id,data in pairs(d.inventory.box) do if (data.am or 0)>0 then InventoryService:useItem(id,{use=data.am}); task.wait(0.3) end end end end) end

local function autoUse(key, on) if not on then return end; loop(10, function() local d=pd(); if not d.inventory or not d.inventory[key] or not d.activeBoosts then return end; for id,data in pairs(d.inventory[key]) do if (data.am or 0)>0 and not(d.activeBoosts[data.nm] and d.activeBoosts[data.nm]>0) then InventoryService:useItem(id,"1"); task.wait(0.3) end end end) end
autoUse("potion", S.AutoUsePotions)
autoUse("fruit", S.AutoUseFruits)
autoUse("smoothie", S.AutoUseSmoothies)
autoUse("activeEvent", S.AutoUseStars)

if S.AutoUseTotems then loop(10, function() local d=pd(); local TC=Knit.GetController("TotemController"); local MC=Knit.GetController("MapController"); local mid=MC:getCurrentMap(true); local act=false; for _,td in pairs(TC:getCurrentTotems()) do if td.mapId==mid then act=true; break end end; if not act and d.inventory and d.inventory.totem then for uuid,data in pairs(d.inventory.totem) do if (data.am or 0)>0 then InventoryService:useItem(uuid,{mapId=mid}); break end end end end) end
if S.AutoRollDice then loop(2, function() local d=pd(); local D=require(RS.Shared.List.Items.AuraDices); for did in pairs(D) do local it=Util.itemUtils.getItemFromName(d,did); if it and it:getAmount()>0 then AuraService:roll(did); return end end end) end
if S.AutoCraftDice then loop(10, function() local ADC=require(RS.Shared.List.AuraDiceCrafting); local d=pd(); for i,r in ipairs(ADC) do local nm=r.item:getName(); local am=r.item:getAmount(); local have=Util.itemUtils.getItemFromName(d,nm); if have and have:getAmount()>=am then AuraService:craftDice(i,math.floor(have:getAmount()/am)); task.wait(0.5) end end end) end
if S.AutoBreakMeteors then loop(3, function() for _,m in ipairs(CollectionService:GetTagged("Meteor")) do local id=m:GetAttribute("meteorId"); if id then EventService.damageMeteor:Fire(id) end end end) end

-- ══════════════════════════════════════════════
-- WEBHOOK
-- ══════════════════════════════════════════════
local whURL = (S.PetWebhook and S.PetWebhook.WebhookURL ~= "" and S.PetWebhook.WebhookURL) or (S.StatsWebhook and S.StatsWebhook.WebhookURL ~= "" and S.StatsWebhook.WebhookURL) or ""

if S.PetWebhook and S.PetWebhook.Enable and whURL ~= "" and requestFunc then
    local rars={}; for _,r in ipairs(S.PetWebhook.Rarities or {}) do rars[r]=true end
    local PM=require(RS.Shared.List.Pets.Pets); local TL=require(RS.Shared.List.Pets.Tiers)
    EggService.openEgg:Connect(function(en,pt)
        local pets=type(en)=="table" and en or pt; if type(pets)~="table" then return end
        task.spawn(function() for _,p in ipairs(pets) do local base=PM[p.nm]; if base and rars[base.rarity] then
            local tier=p.ti or 1; local mult=(base.multiplier or 0)*math.max(1,tier*2-2)*(p.sh and 1.5 or 1)
            local tn=(tier>1 and TL[tier]) and TL[tier].name or "Normal"
            local ping=S.PetWebhook.DiscordUserID~="" and ("<@"..S.PetWebhook.DiscordUserID..">") or ""
            pcall(function() requestFunc({Url=whURL,Method="POST",Headers={["Content-Type"]="application/json"},Body=HttpService:JSONEncode({content=ping,embeds={{title="Pet Hatched",color=0xFFD700,description="```\nPet: "..p.nm.."\nType: "..tn.."\nRarity: "..base.rarity.."\nShiny: "..(p.sh and "Yes" or "No").."\nMult: x"..Functions.suffixes(mult).."\n```",footer={text="RCU Kaitun | "..os.date("%I:%M %p")}}}})}) end)
        end end end)
    end)
end

if S.StatsWebhook and S.StatsWebhook.Enable and whURL ~= "" and requestFunc then
    loop((S.StatsWebhook.IntervalMinutes or 30)*60, function()
        local d=pd(); local honey=0; pcall(function() local h=Util.itemUtils.getItemFromName(d,"honey"); honey=h and h:getAmount() or 0 end)
        local elapsed=os.time()-sessionStart; local ping=(S.PetWebhook and S.PetWebhook.DiscordUserID~="" and ("<@"..S.PetWebhook.DiscordUserID..">")) or ""
        pcall(function() requestFunc({Url=whURL,Method="POST",Headers={["Content-Type"]="application/json"},Body=HttpService:JSONEncode({content=ping,embeds={{title="RCU Stats - "..LP.Name,color=0x5865F2,description="```\n"..table.concat({
            "Session : "..string.format("%02d:%02d:%02d",math.floor(elapsed/3600),math.floor(elapsed%3600/60),elapsed%60),
            "Clicks  : "..Functions.suffixes(d.clicks or 0), "Rebirths: "..Functions.suffixes(d.rebirths or 0),
            "Gems    : "..Functions.suffixes(d.gems or 0), "Honey   : "..Functions.suffixes(honey),
            "Skulls  : "..Functions.suffixes(d.skulls or 0), "Prestige: "..(d.prestige or 0),
            "Eggs    : "..eggsThisSession.." (session)",
        },"\n").."\n```",footer={text="RCU Kaitun | "..os.date("%I:%M %p %m/%d/%Y")}}}})}) end)
    end)
end

-- ══════════════════════════════════════════════
-- REJOIN
-- ══════════════════════════════════════════════
if S.PrivateServerRejoin and S.PrivateServerRejoin.Enable and S.PrivateServerRejoin.ServerCode ~= "" then
    task.spawn(function()
        task.wait(S.PrivateServerRejoin.DelaySeconds or 3600)
        local code=S.PrivateServerRejoin.ServerCode; local m=code:match("code=([%w]+)"); if m then code=m end
        local opts=Instance.new("TeleportOptions"); opts.ReservedServerAccessCode=code
        TeleportService:Teleport(game.PlaceId,LP,opts)
    end)
end
if S.PublicServerRejoin and S.PublicServerRejoin.Enable then
    task.spawn(function()
        task.wait(S.PublicServerRejoin.DelaySeconds or 3600)
        local ok,resp=pcall(function() return HttpService:JSONDecode(game:HttpGet("https://games.roblox.com/v1/games/"..game.PlaceId.."/servers/Public?sortOrder=Asc&limit=100")) end)
        if ok and resp and resp.data then for _,srv in ipairs(resp.data) do if srv.id~=game.JobId and srv.playing<srv.maxPlayers then TeleportService:TeleportToPlaceInstance(game.PlaceId,srv.id,LP); break end end end
    end)
end

print("[RCU Kaitun] All "..52 .." systems running. AFK farming active.")
